package com.vinnichenko.task1.entity.impl;

public enum ApplianceParameter {
    POWER_CONSUMPTION,
    WEIGHT,
    CAPACITY,
    DEPTH,
    HEIGHT,
    WIDTH,
    BATTERY_CAPACITY,
    OS,
    MEMORY_ROM,
    SYSTEM_MEMORY,
    CPU,
    DISPLAY_INCHES,
    FREEZER_CAPACITY,
    OVERALL_CAPACITY,
    NUMBER_OF_SPEAKERS,
    FREQUENCY_RANGE,
    CORD_LENGTH,
    FILTER_TYPE,
    BAG_TYPE,
    WAND_TYPE,
    MOTOR_SPEED_REGULATION,
    CLEANING_WIDTH,
    FLASH_MEMORY_CAPACITY,
    COLOR,
    NUMBER_SPEAKERS
}
